# Generated by Django 2.0 on 2018-04-09 14:28

from django.db import migrations, models
import uuid

from django.conf import settings

# Determine the field type
if getattr(settings, 'MODERATED_OBJECT_PK', "") == "use_uuid":
    field = models.UUIDField(default=uuid.uuid4, editable=False)
else:
    field = models.PositiveIntegerField(null=True, blank=True,
                                            editable=False)


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_auto_20180205_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatedobject',
            name='object_pk',
            field=field,
        ),
    ]
